# List
GET http://localhost:3000/api/blog/post-list?page=1

### Details
GET http://localhost:3000/api/blog/post-details/test

### Details 2
GET http://localhost:3000/api/blog/post-details/piatdesiati-v-Skliantsi-10-Kultovykh-kokteiliv-yaki-pidkoryly-ameryku

### Details prod ip
GET https://api.mixdrinks.org/api/blog/post-details/piatdesiati-v-Skliantsi-10-Kultovykh-kokteiliv-yaki-pidkoryly-ameryku
